# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          hyuns.io
baseurl:        ""
url:            "https://hyuns.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Choi Corder
  url:          https://hyuns.io
  email:        lohremnt@gmail.com
  #github:       iamleejihye
  #twitter:      playpingpong

# Custom vars
version:        3.4.1
#github:
  #repo:         https://github.com/iamleejihye/iamleejihye.github.io